/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Gestor_Producción;
import Controlador.Gestor_Producto;
import Modelo.Producto;
import javax.swing.JOptionPane;

/**
 *
 * @author josek
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        
        JP_info_Productos.removeAll();
        JP_info_Productos.add(JP_Alta_Producto);
        JP_info_Productos.repaint();
        JP_info_Productos.revalidate();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        BG_Buscar_Producciones = new javax.swing.ButtonGroup();
        JTB_Menu = new javax.swing.JTabbedPane();
        JP_Productos = new javax.swing.JPanel();
        JP_botones_Productos = new javax.swing.JPanel();
        JB_Alta_Producto = new javax.swing.JButton();
        JB_Cambiar_Producto = new javax.swing.JButton();
        JB_Baja_Producto = new javax.swing.JButton();
        JP_info_Productos = new javax.swing.JPanel();
        JP_Cambiar_Producto = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTB_Productos = new javax.swing.JTable();
        JL_Info_en_cambiar = new javax.swing.JLabel();
        JL_NNombre = new javax.swing.JLabel();
        JL_NCodigo = new javax.swing.JLabel();
        JTF_NNombre_Producto = new javax.swing.JTextField();
        JTF_NCodigo_Producto = new javax.swing.JTextField();
        JB_Aceptar_CambiarProducto = new javax.swing.JButton();
        JB_Cancelar_CambiarProducto = new javax.swing.JButton();
        LF_Info_CambiarProducto2 = new javax.swing.JLabel();
        JP_Baja_Producto = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTB_Productos1 = new javax.swing.JTable();
        JL_Info_Baja = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        JP_Alta_Producto = new javax.swing.JPanel();
        JL_Nombre_Producto = new javax.swing.JLabel();
        JL_Codigo_Producto = new javax.swing.JLabel();
        JTF_Nombre_Producto = new javax.swing.JTextField();
        JTF_Codigo_Producto = new javax.swing.JTextField();
        JB_Aceptar_NuevoProducto = new javax.swing.JButton();
        JB_Cancelar_NuevoProdu = new javax.swing.JButton();
        JP_MateriaPrima = new javax.swing.JPanel();
        JP_Variedades = new javax.swing.JPanel();
        JP_Proveedores = new javax.swing.JPanel();
        JP_Ventas = new javax.swing.JPanel();
        JP_botones_Ventas = new javax.swing.JPanel();
        JB_Ventas_ComenzarVenta = new javax.swing.JButton();
        JP_info_Ventas = new javax.swing.JPanel();
        JP_Comenzar_Venta = new javax.swing.JPanel();
        JL_info_Venta1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        JT_Ventas_Productos = new javax.swing.JTable();
        JTF_Filtro_Producto = new javax.swing.JTextField();
        JL_info_Venta2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        JT_Ventas_Acumulado = new javax.swing.JTable();
        JL_SignoARS = new javax.swing.JLabel();
        JTF_Ventas_ImpAcc = new javax.swing.JTextField();
        JL_info_Venta3 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        JT_Ventas_Clientes = new javax.swing.JTable();
        JTF_Filtro_Cliente = new javax.swing.JTextField();
        JB_Ventas_Finalizar = new javax.swing.JButton();
        JTF_Ventas_Cancelar = new javax.swing.JButton();
        JP_Producciones = new javax.swing.JPanel();
        JP_botones_Producciones = new javax.swing.JPanel();
        JB_Buscar_Producciones = new javax.swing.JButton();
        JP_info_Producciones = new javax.swing.JPanel();
        JP_Buscar_Producción = new javax.swing.JPanel();
        JRB_Buscar_Produccion_Fecha = new javax.swing.JRadioButton();
        JRB_Buscar_Produccion_Lote = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        JB_Producciones_Aceptar_Busqueda = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(1366, 768));

        JTB_Menu.setBackground(new java.awt.Color(245, 250, 166));

        JP_Productos.setLayout(new java.awt.BorderLayout());

        JP_botones_Productos.setBackground(new java.awt.Color(245, 250, 166));
        JP_botones_Productos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        JB_Alta_Producto.setText("Nuevo Producto");
        JB_Alta_Producto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JB_Alta_Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_Alta_ProductoActionPerformed(evt);
            }
        });

        JB_Cambiar_Producto.setText("Cambiar Producto");
        JB_Cambiar_Producto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JB_Cambiar_Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_Cambiar_ProductoActionPerformed(evt);
            }
        });

        JB_Baja_Producto.setText("Eliminar Producto");
        JB_Baja_Producto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JB_Baja_Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_Baja_ProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JP_botones_ProductosLayout = new javax.swing.GroupLayout(JP_botones_Productos);
        JP_botones_Productos.setLayout(JP_botones_ProductosLayout);
        JP_botones_ProductosLayout.setHorizontalGroup(
            JP_botones_ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_botones_ProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JP_botones_ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_botones_ProductosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JB_Cambiar_Producto))
                    .addGroup(JP_botones_ProductosLayout.createSequentialGroup()
                        .addGroup(JP_botones_ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JB_Alta_Producto)
                            .addComponent(JB_Baja_Producto))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        JP_botones_ProductosLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {JB_Alta_Producto, JB_Baja_Producto, JB_Cambiar_Producto});

        JP_botones_ProductosLayout.setVerticalGroup(
            JP_botones_ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_botones_ProductosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(JB_Alta_Producto)
                .addGap(67, 67, 67)
                .addComponent(JB_Cambiar_Producto)
                .addGap(67, 67, 67)
                .addComponent(JB_Baja_Producto)
                .addContainerGap(529, Short.MAX_VALUE))
        );

        JP_Productos.add(JP_botones_Productos, java.awt.BorderLayout.LINE_START);

        JP_info_Productos.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        JP_info_Productos.setLayout(new java.awt.CardLayout());

        JTB_Productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(JTB_Productos);

        JL_Info_en_cambiar.setText("Los campos dejados en blanco serán rellenados automáticamente.");

        JL_NNombre.setText("Ingrese el nuevo Nombre del Producto:");

        JL_NCodigo.setText("Ingrese el nuevo Código del Producto:");

        JB_Aceptar_CambiarProducto.setText("Aceptar");
        JB_Aceptar_CambiarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        JB_Cancelar_CambiarProducto.setText("Cancelar");
        JB_Cancelar_CambiarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LF_Info_CambiarProducto2.setText("Seleccione un Producto para realizarle una modificación:");

        javax.swing.GroupLayout JP_Cambiar_ProductoLayout = new javax.swing.GroupLayout(JP_Cambiar_Producto);
        JP_Cambiar_Producto.setLayout(JP_Cambiar_ProductoLayout);
        JP_Cambiar_ProductoLayout.setHorizontalGroup(
            JP_Cambiar_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_Cambiar_ProductoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(JL_Info_en_cambiar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_Cambiar_ProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JP_Cambiar_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JL_NNombre)
                    .addComponent(JL_NCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 421, Short.MAX_VALUE)
                .addGroup(JP_Cambiar_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JP_Cambiar_ProductoLayout.createSequentialGroup()
                        .addComponent(JB_Aceptar_CambiarProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JB_Cancelar_CambiarProducto))
                    .addComponent(JTF_NNombre_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTF_NCodigo_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(289, 289, 289))
            .addGroup(JP_Cambiar_ProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(JP_Cambiar_ProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LF_Info_CambiarProducto2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JP_Cambiar_ProductoLayout.setVerticalGroup(
            JP_Cambiar_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_Cambiar_ProductoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(LF_Info_CambiarProducto2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JL_Info_en_cambiar)
                .addGap(18, 18, 18)
                .addGroup(JP_Cambiar_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP_Cambiar_ProductoLayout.createSequentialGroup()
                        .addComponent(JL_NNombre)
                        .addGap(18, 18, 18)
                        .addComponent(JL_NCodigo))
                    .addGroup(JP_Cambiar_ProductoLayout.createSequentialGroup()
                        .addComponent(JTF_NNombre_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JTF_NCodigo_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(JP_Cambiar_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_Aceptar_CambiarProducto)
                    .addComponent(JB_Cancelar_CambiarProducto))
                .addContainerGap(171, Short.MAX_VALUE))
        );

        JP_info_Productos.add(JP_Cambiar_Producto, "card4");

        JTB_Productos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(JTB_Productos1);

        JL_Info_Baja.setText("Seleccine un Producto para eliminarlo:");

        jButton1.setText("Aceptar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton2.setText("Cancelar");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout JP_Baja_ProductoLayout = new javax.swing.GroupLayout(JP_Baja_Producto);
        JP_Baja_Producto.setLayout(JP_Baja_ProductoLayout);
        JP_Baja_ProductoLayout.setHorizontalGroup(
            JP_Baja_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_Baja_ProductoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(87, 87, 87)
                .addComponent(jButton2)
                .addGap(246, 246, 246))
            .addGroup(JP_Baja_ProductoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(JP_Baja_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1170, Short.MAX_VALUE)
                    .addGroup(JP_Baja_ProductoLayout.createSequentialGroup()
                        .addComponent(JL_Info_Baja)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        JP_Baja_ProductoLayout.setVerticalGroup(
            JP_Baja_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_Baja_ProductoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(JL_Info_Baja)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)
                .addGroup(JP_Baja_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(86, 86, 86))
        );

        JP_info_Productos.add(JP_Baja_Producto, "card3");

        JL_Nombre_Producto.setText("Ingrese el Nombre del Producto:");

        JL_Codigo_Producto.setText("Ingrese el Código del Producto:");

        JB_Aceptar_NuevoProducto.setText("Aceptar");
        JB_Aceptar_NuevoProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JB_Aceptar_NuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_Aceptar_NuevoProductoActionPerformed(evt);
            }
        });

        JB_Cancelar_NuevoProdu.setText("Reset");
        JB_Cancelar_NuevoProdu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JB_Cancelar_NuevoProdu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_Cancelar_NuevoProduActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JP_Alta_ProductoLayout = new javax.swing.GroupLayout(JP_Alta_Producto);
        JP_Alta_Producto.setLayout(JP_Alta_ProductoLayout);
        JP_Alta_ProductoLayout.setHorizontalGroup(
            JP_Alta_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_Alta_ProductoLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(JP_Alta_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JL_Nombre_Producto)
                    .addComponent(JL_Codigo_Producto))
                .addGap(194, 194, 194)
                .addGroup(JP_Alta_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JP_Alta_ProductoLayout.createSequentialGroup()
                        .addComponent(JB_Aceptar_NuevoProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(JB_Cancelar_NuevoProdu))
                    .addComponent(JTF_Codigo_Producto)
                    .addComponent(JTF_Nombre_Producto))
                .addContainerGap(569, Short.MAX_VALUE))
        );
        JP_Alta_ProductoLayout.setVerticalGroup(
            JP_Alta_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_Alta_ProductoLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(JP_Alta_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_Nombre_Producto)
                    .addComponent(JTF_Nombre_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(JP_Alta_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_Codigo_Producto)
                    .addComponent(JTF_Codigo_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 502, Short.MAX_VALUE)
                .addGroup(JP_Alta_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_Aceptar_NuevoProducto)
                    .addComponent(JB_Cancelar_NuevoProdu))
                .addGap(85, 85, 85))
        );

        JP_info_Productos.add(JP_Alta_Producto, "card2");

        JP_Productos.add(JP_info_Productos, java.awt.BorderLayout.CENTER);

        JTB_Menu.addTab("Productos", JP_Productos);

        javax.swing.GroupLayout JP_MateriaPrimaLayout = new javax.swing.GroupLayout(JP_MateriaPrima);
        JP_MateriaPrima.setLayout(JP_MateriaPrimaLayout);
        JP_MateriaPrimaLayout.setHorizontalGroup(
            JP_MateriaPrimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1361, Short.MAX_VALUE)
        );
        JP_MateriaPrimaLayout.setVerticalGroup(
            JP_MateriaPrimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 765, Short.MAX_VALUE)
        );

        JTB_Menu.addTab("Materia Prima", JP_MateriaPrima);

        javax.swing.GroupLayout JP_VariedadesLayout = new javax.swing.GroupLayout(JP_Variedades);
        JP_Variedades.setLayout(JP_VariedadesLayout);
        JP_VariedadesLayout.setHorizontalGroup(
            JP_VariedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1361, Short.MAX_VALUE)
        );
        JP_VariedadesLayout.setVerticalGroup(
            JP_VariedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 765, Short.MAX_VALUE)
        );

        JTB_Menu.addTab("Variedades", JP_Variedades);

        javax.swing.GroupLayout JP_ProveedoresLayout = new javax.swing.GroupLayout(JP_Proveedores);
        JP_Proveedores.setLayout(JP_ProveedoresLayout);
        JP_ProveedoresLayout.setHorizontalGroup(
            JP_ProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1361, Short.MAX_VALUE)
        );
        JP_ProveedoresLayout.setVerticalGroup(
            JP_ProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 765, Short.MAX_VALUE)
        );

        JTB_Menu.addTab("Proveedores", JP_Proveedores);

        JP_Ventas.setLayout(new java.awt.BorderLayout());

        JP_botones_Ventas.setBackground(new java.awt.Color(245, 249, 167));
        JP_botones_Ventas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JP_botones_Ventas.setPreferredSize(new java.awt.Dimension(163, 712));

        JB_Ventas_ComenzarVenta.setText("Comenzar Venta");
        JB_Ventas_ComenzarVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JB_Ventas_ComenzarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_Ventas_ComenzarVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JP_botones_VentasLayout = new javax.swing.GroupLayout(JP_botones_Ventas);
        JP_botones_Ventas.setLayout(JP_botones_VentasLayout);
        JP_botones_VentasLayout.setHorizontalGroup(
            JP_botones_VentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_botones_VentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JB_Ventas_ComenzarVenta)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        JP_botones_VentasLayout.setVerticalGroup(
            JP_botones_VentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_botones_VentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JB_Ventas_ComenzarVenta)
                .addContainerGap(723, Short.MAX_VALUE))
        );

        JP_Ventas.add(JP_botones_Ventas, java.awt.BorderLayout.LINE_START);

        JP_info_Ventas.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        JP_info_Ventas.setLayout(new java.awt.CardLayout());

        JL_info_Venta1.setText("Seleccione un Producto para añadir al carrito:");

        JT_Ventas_Productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(JT_Ventas_Productos);

        JTF_Filtro_Producto.setText("Refine su búsqueda por nombre de Producto");

        JL_info_Venta2.setText("Carrito:");

        JT_Ventas_Acumulado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(JT_Ventas_Acumulado);

        JL_SignoARS.setText("$");

        JTF_Ventas_ImpAcc.setText("0,0");

        JL_info_Venta3.setText("Selecionar Cliente:");

        JT_Ventas_Clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(JT_Ventas_Clientes);

        JTF_Filtro_Cliente.setText("Refine su búsqueda por nombre de Cliente");

        JB_Ventas_Finalizar.setText("Finalizar Venta");
        JB_Ventas_Finalizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        JTF_Ventas_Cancelar.setText("Cancelar Venta");
        JTF_Ventas_Cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout JP_Comenzar_VentaLayout = new javax.swing.GroupLayout(JP_Comenzar_Venta);
        JP_Comenzar_Venta.setLayout(JP_Comenzar_VentaLayout);
        JP_Comenzar_VentaLayout.setHorizontalGroup(
            JP_Comenzar_VentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_Comenzar_VentaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JL_SignoARS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JTF_Ventas_ImpAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
            .addGroup(JP_Comenzar_VentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JP_Comenzar_VentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP_Comenzar_VentaLayout.createSequentialGroup()
                        .addGroup(JP_Comenzar_VentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JP_Comenzar_VentaLayout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JTF_Filtro_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(93, 93, 93))
                    .addGroup(JP_Comenzar_VentaLayout.createSequentialGroup()
                        .addGroup(JP_Comenzar_VentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JP_Comenzar_VentaLayout.createSequentialGroup()
                                .addComponent(JL_info_Venta1)
                                .addGap(375, 375, 375)
                                .addComponent(JL_info_Venta2))
                            .addComponent(JL_info_Venta3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTF_Filtro_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JP_Comenzar_VentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JP_Comenzar_VentaLayout.createSequentialGroup()
                                    .addComponent(JB_Ventas_Finalizar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JTF_Ventas_Cancelar))
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        JP_Comenzar_VentaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {JTF_Filtro_Cliente, JTF_Filtro_Producto});

        JP_Comenzar_VentaLayout.setVerticalGroup(
            JP_Comenzar_VentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_Comenzar_VentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JP_Comenzar_VentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_info_Venta1)
                    .addComponent(JL_info_Venta2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JTF_Filtro_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(JP_Comenzar_VentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JP_Comenzar_VentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_SignoARS)
                    .addComponent(JTF_Ventas_ImpAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JL_info_Venta3)
                .addGap(10, 10, 10)
                .addComponent(JTF_Filtro_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(JP_Comenzar_VentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_Ventas_Finalizar)
                    .addComponent(JTF_Ventas_Cancelar))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        JP_info_Ventas.add(JP_Comenzar_Venta, "card7");

        JP_Ventas.add(JP_info_Ventas, java.awt.BorderLayout.CENTER);

        JTB_Menu.addTab("Ventas", JP_Ventas);

        JP_Producciones.setLayout(new java.awt.BorderLayout());

        JP_botones_Producciones.setBackground(new java.awt.Color(245, 249, 167));
        JP_botones_Producciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JP_botones_Producciones.setPreferredSize(new java.awt.Dimension(163, 712));

        JB_Buscar_Producciones.setText("Buscar");
        JB_Buscar_Producciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JB_Buscar_Producciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_Buscar_ProduccionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JP_botones_ProduccionesLayout = new javax.swing.GroupLayout(JP_botones_Producciones);
        JP_botones_Producciones.setLayout(JP_botones_ProduccionesLayout);
        JP_botones_ProduccionesLayout.setHorizontalGroup(
            JP_botones_ProduccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_botones_ProduccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JB_Buscar_Producciones)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        JP_botones_ProduccionesLayout.setVerticalGroup(
            JP_botones_ProduccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_botones_ProduccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JB_Buscar_Producciones)
                .addContainerGap(723, Short.MAX_VALUE))
        );

        JP_Producciones.add(JP_botones_Producciones, java.awt.BorderLayout.LINE_START);

        JP_info_Producciones.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        JP_info_Producciones.setLayout(new java.awt.CardLayout());

        BG_Buscar_Producciones.add(JRB_Buscar_Produccion_Fecha);
        JRB_Buscar_Produccion_Fecha.setText("Por Fecha");

        BG_Buscar_Producciones.add(JRB_Buscar_Produccion_Lote);
        JRB_Buscar_Produccion_Lote.setText("Por Número de Lote");
        JRB_Buscar_Produccion_Lote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_Buscar_Produccion_LoteActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccione un parámetro de búsqueda y complete la información correspondiente:");

        JB_Producciones_Aceptar_Busqueda.setText("Aceptar");
        JB_Producciones_Aceptar_Busqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jTextField1.setText("DD");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setText("MM");

        jTextField3.setText("AAAA");

        jTextField4.setText("Número de Lote");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JP_Buscar_ProducciónLayout = new javax.swing.GroupLayout(JP_Buscar_Producción);
        JP_Buscar_Producción.setLayout(JP_Buscar_ProducciónLayout);
        JP_Buscar_ProducciónLayout.setHorizontalGroup(
            JP_Buscar_ProducciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_Buscar_ProducciónLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(JP_Buscar_ProducciónLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(JP_Buscar_ProducciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JB_Producciones_Aceptar_Busqueda)
                    .addComponent(jLabel1)
                    .addGroup(JP_Buscar_ProducciónLayout.createSequentialGroup()
                        .addGroup(JP_Buscar_ProducciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JRB_Buscar_Produccion_Fecha)
                            .addGroup(JP_Buscar_ProducciónLayout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(138, 138, 138)
                        .addGroup(JP_Buscar_ProducciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JRB_Buscar_Produccion_Lote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField4))))
                .addContainerGap(696, Short.MAX_VALUE))
        );

        JP_Buscar_ProducciónLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField1, jTextField2});

        JP_Buscar_ProducciónLayout.setVerticalGroup(
            JP_Buscar_ProducciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_Buscar_ProducciónLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(JP_Buscar_ProducciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JRB_Buscar_Produccion_Fecha)
                    .addComponent(JRB_Buscar_Produccion_Lote))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JP_Buscar_ProducciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(JB_Producciones_Aceptar_Busqueda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        JP_info_Producciones.add(JP_Buscar_Producción, "card2");

        JP_Producciones.add(JP_info_Producciones, java.awt.BorderLayout.CENTER);

        JTB_Menu.addTab("Producciones", JP_Producciones);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTB_Menu)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTB_Menu)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_Alta_ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_Alta_ProductoActionPerformed
        // TODO add your handling code here:
        JP_info_Productos.removeAll();
        JP_info_Productos.add(JP_Alta_Producto);
        JP_info_Productos.repaint();
        JP_info_Productos.revalidate();
    }//GEN-LAST:event_JB_Alta_ProductoActionPerformed

    private void JB_Cambiar_ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_Cambiar_ProductoActionPerformed
        // TODO add your handling code here:
        JP_info_Productos.removeAll();
        JP_info_Productos.add(JP_Cambiar_Producto);
        JP_info_Productos.repaint();
        JP_info_Productos.revalidate();
    }//GEN-LAST:event_JB_Cambiar_ProductoActionPerformed

    private void JB_Baja_ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_Baja_ProductoActionPerformed
        // TODO add your handling code here:
        JP_info_Productos.removeAll();
        JP_info_Productos.add(JP_Baja_Producto);
        JP_info_Productos.repaint();
        JP_info_Productos.revalidate();        
    }//GEN-LAST:event_JB_Baja_ProductoActionPerformed

    private void JRB_Buscar_Produccion_LoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_Buscar_Produccion_LoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRB_Buscar_Produccion_LoteActionPerformed

    private void JB_Buscar_ProduccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_Buscar_ProduccionesActionPerformed
        // TODO add your handling code here:
        JP_info_Ventas.removeAll();
        JP_info_Ventas.add(JP_Comenzar_Venta);
        JP_info_Ventas.repaint();
        JP_info_Ventas.revalidate();
    }//GEN-LAST:event_JB_Buscar_ProduccionesActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void JB_Ventas_ComenzarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_Ventas_ComenzarVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JB_Ventas_ComenzarVentaActionPerformed

    private void resetCampos() {
        JTF_Nombre_Producto.setText("");
        JTF_Codigo_Producto.setText("");
    }
    
    private void JB_Aceptar_NuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_Aceptar_NuevoProductoActionPerformed
        // TODO add your handling code here:
        String nombre = JTF_Nombre_Producto.getText();
        String cod = JTF_Codigo_Producto.getText();
        
        Producto p = new Producto(nombre, cod);
        
        boolean exito = Gestor_Producto.altaProducto(p);
        
        if ( exito ) {
            String datos= "Código: " + cod + "\nNombre: " + nombre;
            
            // Mostramos el éxito de la operación
            JOptionPane.showMessageDialog(null, "Alta del nuevo producto exitosa: \n\n" + datos +"\n" );
        }
        
        resetCampos();
    }//GEN-LAST:event_JB_Aceptar_NuevoProductoActionPerformed

    private void JB_Cancelar_NuevoProduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_Cancelar_NuevoProduActionPerformed
        // TODO add your handling code here:
        resetCampos();
    }//GEN-LAST:event_JB_Cancelar_NuevoProduActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BG_Buscar_Producciones;
    private javax.swing.JButton JB_Aceptar_CambiarProducto;
    private javax.swing.JButton JB_Aceptar_NuevoProducto;
    private javax.swing.JButton JB_Alta_Producto;
    private javax.swing.JButton JB_Baja_Producto;
    private javax.swing.JButton JB_Buscar_Producciones;
    private javax.swing.JButton JB_Cambiar_Producto;
    private javax.swing.JButton JB_Cancelar_CambiarProducto;
    private javax.swing.JButton JB_Cancelar_NuevoProdu;
    private javax.swing.JButton JB_Producciones_Aceptar_Busqueda;
    private javax.swing.JButton JB_Ventas_ComenzarVenta;
    private javax.swing.JButton JB_Ventas_Finalizar;
    private javax.swing.JLabel JL_Codigo_Producto;
    private javax.swing.JLabel JL_Info_Baja;
    private javax.swing.JLabel JL_Info_en_cambiar;
    private javax.swing.JLabel JL_NCodigo;
    private javax.swing.JLabel JL_NNombre;
    private javax.swing.JLabel JL_Nombre_Producto;
    private javax.swing.JLabel JL_SignoARS;
    private javax.swing.JLabel JL_info_Venta1;
    private javax.swing.JLabel JL_info_Venta2;
    private javax.swing.JLabel JL_info_Venta3;
    private javax.swing.JPanel JP_Alta_Producto;
    private javax.swing.JPanel JP_Baja_Producto;
    private javax.swing.JPanel JP_Buscar_Producción;
    private javax.swing.JPanel JP_Cambiar_Producto;
    private javax.swing.JPanel JP_Comenzar_Venta;
    private javax.swing.JPanel JP_MateriaPrima;
    private javax.swing.JPanel JP_Producciones;
    private javax.swing.JPanel JP_Productos;
    private javax.swing.JPanel JP_Proveedores;
    private javax.swing.JPanel JP_Variedades;
    private javax.swing.JPanel JP_Ventas;
    private javax.swing.JPanel JP_botones_Producciones;
    private javax.swing.JPanel JP_botones_Productos;
    private javax.swing.JPanel JP_botones_Ventas;
    private javax.swing.JPanel JP_info_Producciones;
    private javax.swing.JPanel JP_info_Productos;
    private javax.swing.JPanel JP_info_Ventas;
    private javax.swing.JRadioButton JRB_Buscar_Produccion_Fecha;
    private javax.swing.JRadioButton JRB_Buscar_Produccion_Lote;
    private javax.swing.JTabbedPane JTB_Menu;
    private javax.swing.JTable JTB_Productos;
    private javax.swing.JTable JTB_Productos1;
    private javax.swing.JTextField JTF_Codigo_Producto;
    private javax.swing.JTextField JTF_Filtro_Cliente;
    private javax.swing.JTextField JTF_Filtro_Producto;
    private javax.swing.JTextField JTF_NCodigo_Producto;
    private javax.swing.JTextField JTF_NNombre_Producto;
    private javax.swing.JTextField JTF_Nombre_Producto;
    private javax.swing.JButton JTF_Ventas_Cancelar;
    private javax.swing.JTextField JTF_Ventas_ImpAcc;
    private javax.swing.JTable JT_Ventas_Acumulado;
    private javax.swing.JTable JT_Ventas_Clientes;
    private javax.swing.JTable JT_Ventas_Productos;
    private javax.swing.JLabel LF_Info_CambiarProducto2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
